### ISSUE TITLE
There is no header files for kernel 6.3.3

### ISSUE THREAD

**Issue by easy-and-simple** [armbian/community#15]
There is no header files for kernel 6.3.3 and modules then need kernel files to be build van be compiled and installed

**Comment by igorpecovnik** [comment]
Headers are stored in package repository, but in case of unofficial community builds, repository is not getting updated (yet). In order to have header, you need to make image from sources and enable headers installing (how? -> docs.armbian.com).

**Comment by easy-and-simple** [comment]
Why when these community images are build headers installing is not enabled, and I need to build it by myself and to enable il?
If you mean armbian build it is not working even with no_apt_cacher option.
In general nothing works in armbian. All features of armbian-config  are not working. It cant install other kerneks, cant install rdp and so on. It starts to download something, but it can't.
I tried community build with 6.3.3 kernel on rock3a board and performance is better than official builds, but not because of new kernel. because I installed 6.1 kernel for which there are headers and this didn't impact the performance, so I suppose there is some new video driver included in community releases

**Comment by igorpecovnik** [comment]
Since this is unsupported community builds, you need to address your question to community. Start here: https://forum.armbian.com/ then move to kernel mailing lists, Debian forums, ...

> Why when these community images are build

- that developers have ready to flash images made with official builds system which they can regularly check and see what is the support status and if problems are in areas where they might have a solution, that lead to solving problems. They sent a fix and that fix gets merged and eventually you are happy. This happens in periods of months and years, so you probably don't notice.
- to prove that build framework is fully operational (and your vague complains without logs can be 100% ignored)
- that end users who wants to check latest and greatest have something to play with. If you expect support, you are abusing support contract,
- to match support level with rolling Linux distributions (Arch/Manjaro and similar) that are doing nothing and where nobody and everyone is responsible for support at the same time.

> headers installing is not enabled

Because pre-installing headers to images is not desirable to be installed by default. It takes space and very little people are using this.

> and I need to build it by myself and to enable il?

This is just a tip.

> If you mean armbian build it is not working even with no_apt_cacher option.

Image you are running proves that it works. You are doing something wrong. Since this place is wrong to deal with this and since you didn't supplied logs, I won't be wasting more time.

> In general nothing works in armbian.

Generated images, automated testing and tens of thousands of users proves that you are wrong in this observation. But ofc there are problems. Open source software is made by thousands of people.

> All features of armbian-config are not working.

If you are using unsupported images, all complains goes to /dev/null It is expected this will fail. armbian-config is end user tool which have to work in supported images. There - it works.

> I suppose there is some new video driver included in community releases

Since there is no support, I can't answer to this question even I would know.

**Comment by easy-and-simple** [comment]
On supported images armbian-config is not working too
Armbian build is not working at all. People dont waste time to report it because you are rude and it is waste of time to explain to you anything. 
Armbian build asks me for username and password to authenticate with git but always authentication is unsuccessful because as is written in error message username-pass authentication is not supported since year 2021. I tried to authenticate with gh but is doesn't help because armbian-build is not working. 
Few days ago using brebuild images worked, but now it's not

**Comment by igorpecovnik** [comment]
> People dont waste time to report it because

Without giving you right to record issues, average issue resolving rate is 450 days. Ofc with other distros this is a lot worse.

![resolving](https://github.com/armbian/community/assets/6281704/c6b099c7-5900-4bb7-a2e3-48c401480f61)

> Armbian build is not working at all.

It is working for us. If its not working for you, open a ticket at right place and wait. Just like everyone else.
